# Generated by Django 5.1.5 on 2025-01-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0003_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna'), (3, 'Inna')], default=3),
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='opis',
            field=models.TextField(editable=False),
        ),
    ]
