# Generated by Django 5.1.5 on 2025-01-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0009_alter_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
