# Generated by Django 5.1.5 on 2025-01-26 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0012_druzyna_alter_osoba_imie_alter_osoba_nazwisko_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('view_postacie_other_owner', 'Pozwala zobaczyć modele Postacie innych właścicieli')]},
        ),
    ]
